<a href="https://colab.research.google.com/github/dnjsqls820/dnjsqls820/blob/main/%EA%B0%95%EC%9D%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


평균 기온값의 최대값 최소값 출력

In [16]:
import csv
f = open('/content/drive/MyDrive/실습/temp_day.csv', encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = [ ]
for row in data:
    temp.append(float(row[1]))
print(temp)
print(min(temp),max(temp))

[-3.9, -6.7, -4.3, -1.3, -1.9, -2.5, -2.8, -2.2, -1.6, 0.3, 1.3, 0.5, -7.4, -7.7, -6.4, -4.8, -1.0, -2.0, -5.8, -5.6, -5.3, -5.0, -2.7, 0.3, 2.0, 4.6, 2.8, 1.3, -1.1, -2.7]
-7.7 4.6


1단계 : 유동인구 데이터를 컴퓨터로 저장한 수 출력

In [ ]:
#은재가 조사한 일주일간 유동 인구 데이터 (월요일~일요일)
a = [242, 256, 237, 223, 263, 81, 46]   #리스트에 유동 인구 데이터 초기화
print('A=',a)                           #출력하기

2단계: 유동인구 데이터의 총합과 평균
일주일간의 유동 총 인구수와 평균을 우선 살펴보기로 하자

In [23]:
a = [242, 256, 237, 223, 263, 81, 46]   #리스트에 유동 인구 데이터 초기화
print('A=',a)                           #출력하기
n = len(a)
my_sum = 0
my_avg = 0
i = 0

for i in range(0,n):
    my_sum = my_sum + a[i]

my_avg=my_sum/n
print('Total Sum:', my_sum)
print('Total Average: ', my_avg)

A= [242, 256, 237, 223, 263, 81, 46]
Total Sum: 1348
Total Average:  192.57142857142858


In [3]:
a = [242, 256, 237, 223, 263, 81, 46]
print('A=',a)
import matplotlib.pyplot as plt
from matplotlib import font_manager, rc


rc('font', family = 'NanumBarunGothic')

x_data = ['MON', 'TUE', 'WED', 'THR', 'FRI', 'SAT', 'SUN']
#그래프의 제목 붙이기
plt.title('일주일간 유동 인구수 데이터', fontsize = 16)
plt.xlabel('요일', fontsize = 12)
plt.ylabel('유동 인구수', fontsize = 12)
#꺽은선 그래프 그리기
plt.scatter(x_data, a)
plt.plot(x_data, a)
plt.show()

A= [242, 256, 237, 223, 263, 81, 46]


In [4]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 37 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 3s (2,918 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package fonts-nanum.
(Reading database ... 155229 files and d

In [48]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []
a = 0
for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))

print(temp)
print(ice)


[-2.1, -2.5, -2.1, -0.7, 0.2, -1.3, -0.5, -0.7, -2.9, 0.5, 2.1, 3.0, 1.3, 1.0, 0.9, -3.2, 0.4, 0.8, 2.9, 1.6, 0.5, 2.6, 3.1, 0.7, -0.4, -1.8, -0.2, 2.6, 0.0, 3.5, 0.3, -1.3, 2.1, 5.6, 2.5, 2.9, 5.6, 2.1, -2.0, -1.7, -1.4, -0.8, 0.1, 0.3, 0.6, 2.0, -0.3, -0.2, 2.2, 2.9, 2.8, 2.7, 3.9, 5.0, 6.1, 6.0, 5.4, 7.1, 6.8, 6.0, 6.9, 8.7, 8.8, 8.2, 8.8, 6.5, 6.1, 7.9, 7.8, 6.4, 5.8, 3.9, 5.2, 5.8, 5.8, 6.6, 7.5, 10.7, 11.4, 9.8, 5.2, 4.2, 4.7, 7.2, 10.5, 12.8, 10.6, 10.6, 7.2, 5.4, 5.7, 6.7, 7.4, 9.9, 11.7, 11.6, 12.5, 11.8, 9.3, 7.2, 8.8, 10.7, 11.6, 10.2, 11.1, 14.2, 15.5, 15.3, 12.8, 14.7, 16.5, 17.6, 16.8, 17.3, 13.5, 9.4, 11.4, 12.1, 11.3, 14.6, 15.4, 16.0, 16.7, 17.6, 18.9, 14.0, 13.9, 15.7, 17.1, 17.6, 18.5, 18.4, 17.9, 19.8, 20.3, 21.4, 21.3, 18.8, 19.5, 17.0, 17.0, 19.2, 20.9, 22.9, 23.3, 23.2, 18.6, 17.8, 19.7, 20.5, 18.6, 18.9, 20.6, 22.0, 23.1, 22.9, 21.1, 18.6, 20.1, 19.7, 18.3, 18.8, 19.7, 21.2, 20.2, 20.4, 20.2, 21.3, 21.3, 22.2, 23.4, 22.8, 21.7, 21.6, 22.5, 23.6, 21.1, 23.8, 23.6

1단계: 평균 기온 값의 최솟값과 최댓값을 찾아 출력

In [49]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []
for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))
print(min(temp), max(temp))

-4.1 28.8


2단계: 도수분포 구간을 설정하여 출력

In [50]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []
for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))
#평균 기온 값을 기준으로 도수분포 구간 설정하기
import numpy as np

bins = np.arange(min(temp), max(temp), 5)
print(bins)

[-4.1  0.9  5.9 10.9 15.9 20.9 25.9]


3단계: 도수분포 구간을 재설정하여 출력

In [51]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []
for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))
#평균 기온 값을 기준으로 도수분포 구간 설정하기
import numpy as np

bins = np.arange(min(temp), max(temp)+5,5)
print(bins)

[-4.1  0.9  5.9 10.9 15.9 20.9 25.9 30.9]


4단계: 각 계급에 해당하는 도수값 확인 후 출력

In [52]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []
for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))
#평균 기온 값을 기준으로 도수분포 구간 설정하기
import numpy as np
bins = np.arange(min(temp),max(temp)+5,5)
hist, bins = np.histogram(temp, bins)
print(hist)
print(bins)

[40 59 54 48 52 84 28]
[-4.1  0.9  5.9 10.9 15.9 20.9 25.9 30.9]


5단계: 계급별 아이스크림 쇼핑 클릭량 합계

In [54]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []

for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))

import numpy as np

bins = np.arange(min(temp),max(temp)+5,5)
hist, bins = np.histogram(temp, bins)

ice_buy = np.zeros(7)

for i in range(0, len(temp)):
    if bins[0] <= temp[i] and temp[i] < bins[1]:
        ice_buy[0] = ice_buy[0] + ice[i]
    elif bins[1] <= temp[i] and temp[i] < bins[2]:
        ice_buy[1] = ice_buy[1] + ice[i]
    elif bins[2] <= temp[i] and temp[i] < bins[3]:
        ice_buy[2] = ice_buy[2] + ice[i]
    elif bins[3] <= temp[i] and temp[i] < bins[4]:
        ice_buy[3] = ice_buy[3] + ice[i]
    elif bins[4] <= temp[i] and temp[i] < bins[5]:
        ice_buy[4] = ice_buy[4] + ice[i]
    elif bins[5] <= temp[i] and temp[i] < bins[6]:
        ice_buy[5] = ice_buy[5] + ice[i]
    else:
        ice_buy[6] = ice_buy[6] + ice[i]
print(ice_buy)

[1106. 1659. 1574. 1596. 2866. 4613. 1718.]


6단계: 도수분포 구간을 재설정하여 출력

In [53]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []

for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))

import numpy as np

bins = np.arange(min(temp),max(temp)+5,5)
hist, bins = np.histogram(temp, bins)

ice_buy = np.zeros(7)

for i in range(0, len(temp)):
    if bins[0] <= temp[i] and temp[i] < bins[1]:
        ice_buy[0] = ice_buy[0] + ice[i]
    elif bins[1] <= temp[i] and temp[i] < bins[2]:
        ice_buy[1] = ice_buy[1] + ice[i]
    elif bins[2] <= temp[i] and temp[i] < bins[3]:
        ice_buy[2] = ice_buy[2] + ice[i]
    elif bins[3] <= temp[i] and temp[i] < bins[4]:
        ice_buy[3] = ice_buy[3] + ice[i]
    elif bins[4] <= temp[i] and temp[i] < bins[5]:
        ice_buy[4] = ice_buy[4] + ice[i]
    elif bins[5] <= temp[i] and temp[i] < bins[6]:
        ice_buy[5] = ice_buy[5] + ice[i]
    else:
        ice_buy[6] = ice_buy[6] + ice[i]

ice_buy_a = np.zeros(7)

for i in range(0,len(ice_buy)):
    ice_buy_a[i] = ice_buy[i] / hist[i]

for i in range(0, len(ice_buy)):
    print('%0.2f'% ice_buy_a[i])

27.65
28.12
29.15
33.25
55.12
54.92
61.36


In [58]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []

for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))

import numpy as np

bins = np.arange(min(temp),max(temp)+5,5)
hist, bins = np.histogram(temp, bins)

ice_buy = np.zeros(7)

for i in range(0, len(temp)):
    if bins[0] <= temp[i] and temp[i] < bins[1]:
        ice_buy[0] = ice_buy[0] + ice[i]
    elif bins[1] <= temp[i] and temp[i] < bins[2]:
        ice_buy[1] = ice_buy[1] + ice[i]
    elif bins[2] <= temp[i] and temp[i] < bins[3]:
        ice_buy[2] = ice_buy[2] + ice[i]
    elif bins[3] <= temp[i] and temp[i] < bins[4]:
        ice_buy[3] = ice_buy[3] + ice[i]
    elif bins[4] <= temp[i] and temp[i] < bins[5]:
        ice_buy[4] = ice_buy[4] + ice[i]
    elif bins[5] <= temp[i] and temp[i] < bins[6]:
        ice_buy[5] = ice_buy[5] + ice[i]
    else:
        ice_buy[6] = ice_buy[6] + ice[i]

ice_buy_a = np.zeros(7)

for i in range(0,len(ice_buy)):
    ice_buy_a[i] = ice_buy[i] / hist[i]


import matplotlib.pyplot as plt
plt.xlabel('Average temperature')
plt.ylabel('Number of ice cream shopping')
plt.bar(bins[0:7],ice_buy_a, width = 2, align = 'edge')
plt.xticks(bins[0:7])
plt.show()

In [59]:
import csv
f = open('/content/drive/MyDrive/실습/temp_ice.csv',encoding='euc-kr')
data = csv.reader(f)
header = next(data)
temp = []
ice = []

for row in data:
    temp.append(float(row[1]))
    ice.append(int(row[4]))

import numpy as np

bins = np.arange(min(temp),max(temp)+5,5)
hist, bins = np.histogram(temp, bins)

ice_buy = np.zeros(7)

for i in range(0, len(temp)):
    if bins[0] <= temp[i] and temp[i] < bins[1]:
        ice_buy[0] = ice_buy[0] + ice[i]
    elif bins[1] <= temp[i] and temp[i] < bins[2]:
        ice_buy[1] = ice_buy[1] + ice[i]
    elif bins[2] <= temp[i] and temp[i] < bins[3]:
        ice_buy[2] = ice_buy[2] + ice[i]
    elif bins[3] <= temp[i] and temp[i] < bins[4]:
        ice_buy[3] = ice_buy[3] + ice[i]
    elif bins[4] <= temp[i] and temp[i] < bins[5]:
        ice_buy[4] = ice_buy[4] + ice[i]
    elif bins[5] <= temp[i] and temp[i] < bins[6]:
        ice_buy[5] = ice_buy[5] + ice[i]
    else:
        ice_buy[6] = ice_buy[6] + ice[i]

ice_buy_a = np.zeros(7)

for i in range(0,len(ice_buy)):
    ice_buy_a[i] = ice_buy[i] / hist[i]

    
import matplotlib.pyplot as plt
plt.xlabel('Average temperature')
plt.ylabel('Number of ice cream shopping')
plt.bar(bins[0:7],ice_buy_a, width = 2, align = 'edge')
plt.xticks(bins[0:7])
plt.show()

In [69]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/실습/temp_ice.csv',encoding = 'euc-kr')
print(df.head(5))
#데이터를 입력 변수와 출력 변수로 나누기
import numpy as np
data = np.array(df)
X = data[:,1]
Y = data[:,-1]
# 2단계 입력 변수와 출력 변수 각가의 평균(mean) 구하기
mean_x = np.mean(X)
mean_y = np.mean(Y)
#X변수의 개수 구하기
n = len(X)
#최소제곱법을 이용하여 beta0과 beta1구하기
temp1 = 0
temp2 = 0
for i in range(n):
    temp1 += (X[i] - mean_x) * (Y[i] - mean_y)
    temp2 += (X[i] - mean_x) **2
beta1 = temp1 / temp2
beta0 = mean_y - (beta1 * mean_x)
# 계산결과 출력하기
print('기울기(beta1:) {0}, 절편(beta0): {1}'.format(beta1,beta0))

           날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  아이스크림/빙수
0  2019-01-01     -2.1     -5.8      2.1        27
1  2019-01-02     -2.5     -7.0      3.2        27
2  2019-01-03     -2.1     -7.7      5.0        25
3  2019-01-04     -0.7     -7.3      5.3        25
4  2019-01-05      0.2     -4.6      5.3        26
기울기(beta1:) 1.3678769756404305, 절편(beta0): 22.975829882004522


In [11]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/실습/temp_ice.csv',encoding = 'euc-kr')
#데이터를 입력 변수와 출력 변수로 나누기
import numpy as np
data = np.array(df)
X = data[:,1]
Y = data[:,-1]
# 2단계 입력 변수와 출력 변수 각가의 평균(mean) 구하기
mean_x = np.mean(X)
mean_y = np.mean(Y)
#X변수의 개수 구하기
n = len(X)
#최소제곱법을 이용하여 beta0과 beta1구하기
temp1 = 0
temp2 = 0
for i in range(n):
    temp1 += (X[i] - mean_x) * (Y[i] - mean_y)
    temp2 += (X[i] - mean_x) **2
beta1 = temp1 / temp2
beta0 = mean_y - (beta1 * mean_x)
import matplotlib.pyplot as plt
Y_pred = beta0 + beta1 * X


plt.title('Avg_temp & Clicks')
plt.xlabel('Average temperature(C)')
plt.ylabel('Clicks')
plt.plot(X,Y,'k.')
plt.plot(X,Y_pred,color = 'red')
plt.axis([-4,30,20,100])
plt.grid()
plt.show()

In [12]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/실습/temp_ice.csv',encoding = 'euc-kr')
#데이터를 입력 변수와 출력 변수로 나누기
import numpy as np
data = np.array(df)
X = data[:,1]
Y = data[:,-1]
# 2단계 입력 변수와 출력 변수 각가의 평균(mean) 구하기
mean_x = np.mean(X)
mean_y = np.mean(Y)
#X변수의 개수 구하기
n = len(X)
#최소제곱법을 이용하여 beta0과 beta1구하기
temp1 = 0
temp2 = 0
for i in range(n):
    temp1 += (X[i] - mean_x) * (Y[i] - mean_y)
    temp2 += (X[i] - mean_x) **2
beta1 = temp1 / temp2
beta0 = mean_y - (beta1 * mean_x)
def RMSE(beta0, beta1, x,y):
    RMSE = np.sqrt(((y-(beta0 + beta1 * x)) ** 2).mean())
    return RMSE

results = RMSE(beta0,beta1,X,Y)
print('손실값 결과는? {0}'.format(results))

손실값 결과는? 13.890619172550625


In [13]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/실습/temp_ice.csv',encoding = 'euc-kr')
#데이터를 입력 변수와 출력 변수로 나누기
import numpy as np
data = np.array(df)
X = data[:,1]
Y = data[:,-1]
# 2단계 입력 변수와 출력 변수 각가의 평균(mean) 구하기
mean_x = np.mean(X)
mean_y = np.mean(Y)
#X변수의 개수 구하기
n = len(X)
#최소제곱법을 이용하여 beta0과 beta1구하기
temp1 = 0
temp2 = 0
for i in range(n):
    temp1 += (X[i] - mean_x) * (Y[i] - mean_y)
    temp2 += (X[i] - mean_x) **2
beta1 = temp1 / temp2
beta0 = mean_y - (beta1 * mean_x)
def Regression(beta0, beta1, X):
    y_pred = beta0 + beta1 * X
    return y_pred

my_temp = float(input('안녕하세요. 오늘의 평균 기온을 입력해 주세요. :'))
predicted_value = Regression(beta0,beta1,my_temp)
print('아이스크림 쇼핑 크릭량은 100점을 기준으로 {0} 만큼 예상됩니다.'.format(predicted_value))

안녕하세요. 오늘의 평균 기온을 입력해 주세요. :30
아이스크림 쇼핑 크릭량은 100점을 기준으로 64.01213915121744 만큼 예상됩니다.
